"""
Create folder structure matching Geofabrik OSM data organization
This creates directories for all continents, countries, and regions
"""

from pathlib import Path

def create_folder_structure():
    base = Path(__file__).parent.parent / "public" / "data" / "countries"
    
    # Structure based on Geofabrik's data organization
    structure = {
        "Africa": {
            "Algeria": {},
            "Angola": {},
            "Benin": {},
            "Botswana": {},
            "Burkina_Faso": {},
            "Burundi": {},
            "Cameroon": {},
            "Cape_Verde": {},
            "Central_African_Republic": {},
            "Chad": {},
            "Comoros": {},
            "Congo_Brazzaville": {},
            "Congo_Kinshasa": {},
            "Djibouti": {},
            "Egypt": {},
            "Equatorial_Guinea": {},
            "Eritrea": {},
            "Ethiopia": {},
            "Gabon": {},
            "Ghana": {},
            "Guinea": {},
            "Guinea_Bissau": {},
            "Ivory_Coast": {},
            "Kenya": {},
            "Lesotho": {},
            "Liberia": {},
            "Libya": {},
            "Madagascar": {},
            "Malawi": {},
            "Mali": {},
            "Mauritania": {},
            "Mauritius": {},
            "Morocco": {},
            "Mozambique": {},
            "Namibia": {},
            "Niger": {},
            "Nigeria": {},
            "Rwanda": {},
            "Saint_Helena_Ascension_Tristan_da_Cunha": {},
            "Sao_Tome_and_Principe": {},
            "Senegal": {},
            "Seychelles": {},
            "Sierra_Leone": {},
            "Somalia": {},
            "South_Africa": {},
            "South_Sudan": {},
            "Sudan": {},
            "Swaziland": {},
            "Tanzania": {},
            "Togo": {},
            "Tunisia": {},
            "Uganda": {},
            "Zambia": {},
            "Zimbabwe": {}
        },
        
        "Asia": {
            "Afghanistan": {},
            "Armenia": {},
            "Azerbaijan": {},
            "Bangladesh": {},
            "Bhutan": {},
            "Cambodia": {},
            "China": {
                "Anhui": {},
                "Beijing": {},
                "Chongqing": {},
                "Fujian": {},
                "Gansu": {},
                "Guangdong": {},
                "Guangxi": {},
                "Guizhou": {},
                "Hainan": {},
                "Hebei": {},
                "Heilongjiang": {},
                "Henan": {},
                "Hong_Kong": {},
                "Hubei": {},
                "Hunan": {},
                "Inner_Mongolia": {},
                "Jiangsu": {},
                "Jiangxi": {},
                "Jilin": {},
                "Liaoning": {},
                "Macau": {},
                "Ningxia": {},
                "Qinghai": {},
                "Shaanxi": {},
                "Shandong": {},
                "Shanghai": {},
                "Shanxi": {},
                "Sichuan": {},
                "Tianjin": {},
                "Tibet": {},
                "Xinjiang": {},
                "Yunnan": {},
                "Zhejiang": {}
            },
            "Georgia": {},
            "India": {
                "Andaman_and_Nicobar": {},
                "Andhra_Pradesh": {},
                "Arunachal_Pradesh": {},
                "Assam": {},
                "Bihar": {},
                "Chandigarh": {},
                "Chhattisgarh": {},
                "Dadra_and_Nagar_Haveli": {},
                "Daman_and_Diu": {},
                "Delhi": {},
                "Goa": {},
                "Gujarat": {},
                "Haryana": {},
                "Himachal_Pradesh": {},
                "Jammu_and_Kashmir": {},
                "Jharkhand": {},
                "Karnataka": {},
                "Kerala": {},
                "Lakshadweep": {},
                "Madhya_Pradesh": {},
                "Maharashtra": {},
                "Manipur": {},
                "Meghalaya": {},
                "Mizoram": {},
                "Nagaland": {},
                "Odisha": {},
                "Puducherry": {},
                "Punjab": {},
                "Rajasthan": {},
                "Sikkim": {},
                "Tamil_Nadu": {},
                "Telangana": {},
                "Tripura": {},
                "Uttar_Pradesh": {},
                "Uttarakhand": {},
                "West_Bengal": {}
            },
            "Indonesia": {},
            "Iran": {},
            "Iraq": {},
            "Israel_and_Palestine": {},
            "Japan": {
                "Chubu": {},
                "Chugoku": {},
                "Hokkaido": {},
                "Kansai": {},
                "Kanto": {},
                "Kyushu": {},
                "Shikoku": {},
                "Tohoku": {}
            },
            "Jordan": {},
            "Kazakhstan": {},
            "Kyrgyzstan": {},
            "Laos": {},
            "Lebanon": {},
            "Malaysia": {},
            "Maldives": {},
            "Mongolia": {},
            "Myanmar": {},
            "Nepal": {},
            "North_Korea": {},
            "Pakistan": {},
            "Philippines": {},
            "Singapore": {},
            "South_Korea": {},
            "Sri_Lanka": {},
            "Syria": {},
            "Taiwan": {},
            "Tajikistan": {},
            "Thailand": {},
            "Turkmenistan": {},
            "Uzbekistan": {},
            "Vietnam": {},
            "Yemen": {}
        },
        
        "Australia_Oceania": {
            "Australia": {
                "Australian_Capital_Territory": {},
                "New_South_Wales": {},
                "Northern_Territory": {},
                "Queensland": {},
                "South_Australia": {},
                "Tasmania": {},
                "Victoria": {},
                "Western_Australia": {}
            },
            "Cook_Islands": {},
            "Fiji": {},
            "Kiribati": {},
            "Marshall_Islands": {},
            "Micronesia": {},
            "Nauru": {},
            "New_Caledonia": {},
            "New_Zealand": {},
            "Niue": {},
            "Palau": {},
            "Papua_New_Guinea": {},
            "Pitcairn_Islands": {},
            "Samoa": {},
            "Solomon_Islands": {},
            "Tokelau": {},
            "Tonga": {},
            "Tuvalu": {},
            "Vanuatu": {}
        },
        
        "Central_America": {
            "Belize": {},
            "Costa_Rica": {},
            "El_Salvador": {},
            "Guatemala": {},
            "Honduras": {},
            "Nicaragua": {},
            "Panama": {}
        },
        
        "Europe": {
            "Albania": {},
            "Andorra": {},
            "Austria": {},
            "Belarus": {},
            "Belgium": {},
            "Bosnia_Herzegovina": {},
            "Bulgaria": {},
            "Croatia": {},
            "Cyprus": {},
            "Czech_Republic": {},
            "Denmark": {},
            "Estonia": {},
            "Faroe_Islands": {},
            "Finland": {},
            "France": {
                "Alsace": {},
                "Aquitaine": {},
                "Auvergne": {},
                "Basse_Normandie": {},
                "Bourgogne": {},
                "Bretagne": {},
                "Centre": {},
                "Champagne_Ardenne": {},
                "Corse": {},
                "Franche_Comte": {},
                "Guadeloupe": {},
                "Guyane": {},
                "Haute_Normandie": {},
                "Ile_de_France": {},
                "Languedoc_Roussillon": {},
                "Limousin": {},
                "Lorraine": {},
                "Martinique": {},
                "Mayotte": {},
                "Midi_Pyrenees": {},
                "Nord_Pas_de_Calais": {},
                "Pays_de_la_Loire": {},
                "Picardie": {},
                "Poitou_Charentes": {},
                "Provence_Alpes_Cote_d_Azur": {},
                "Reunion": {},
                "Rhone_Alpes": {}
            },
            "Germany": {
                "Baden_Wuerttemberg": {},
                "Bayern": {
                    "Mittelfranken": {},
                    "Niederbayern": {},
                    "Oberbayern": {},
                    "Oberfranken": {},
                    "Oberpfalz": {},
                    "Schwaben": {},
                    "Unterfranken": {}
                },
                "Berlin": {},
                "Brandenburg": {},
                "Bremen": {},
                "Hamburg": {},
                "Hessen": {},
                "Mecklenburg_Vorpommern": {},
                "Niedersachsen": {},
                "Nordrhein_Westfalen": {
                    "Arnsberg": {},
                    "Detmold": {},
                    "Duesseldorf": {},
                    "Koeln": {},
                    "Muenster": {}
                },
                "Rheinland_Pfalz": {},
                "Saarland": {},
                "Sachsen": {},
                "Sachsen_Anhalt": {},
                "Schleswig_Holstein": {},
                "Thueringen": {}
            },
            "Greece": {},
            "Hungary": {},
            "Iceland": {},
            "Ireland": {},
            "Isle_of_Man": {},
            "Italy": {
                "Abruzzo": {},
                "Basilicata": {},
                "Calabria": {},
                "Campania": {},
                "Emilia_Romagna": {},
                "Friuli_Venezia_Giulia": {},
                "Lazio": {},
                "Liguria": {},
                "Lombardia": {},
                "Marche": {},
                "Molise": {},
                "Piemonte": {},
                "Puglia": {},
                "Sardegna": {},
                "Sicilia": {},
                "Toscana": {},
                "Trentino_Alto_Adige": {},
                "Umbria": {},
                "Valle_d_Aosta": {},
                "Veneto": {}
            },
            "Kosovo": {},
            "Latvia": {},
            "Liechtenstein": {},
            "Lithuania": {},
            "Luxembourg": {},
            "Macedonia": {},
            "Malta": {},
            "Moldova": {},
            "Monaco": {},
            "Montenegro": {},
            "Netherlands": {},
            "Norway": {},
            "Poland": {},
            "Portugal": {},
            "Romania": {},
            "Russia": {
                "Central_District": {},
                "Crimean_District": {},
                "Far_Eastern_District": {},
                "Kaliningrad": {},
                "North_Caucasian_District": {},
                "Northwestern_District": {},
                "Siberian_District": {},
                "South_District": {},
                "Ural_District": {},
                "Volga_District": {}
            },
            "Serbia": {},
            "Slovakia": {},
            "Slovenia": {},
            "Spain": {
                "Andalucia": {},
                "Aragon": {},
                "Asturias": {},
                "Baleares": {},
                "Canarias": {},
                "Cantabria": {},
                "Castilla_La_Mancha": {},
                "Castilla_y_Leon": {},
                "Cataluna": {},
                "Ceuta": {},
                "Extremadura": {},
                "Galicia": {},
                "La_Rioja": {},
                "Madrid": {},
                "Melilla": {},
                "Murcia": {},
                "Navarra": {},
                "Pais_Vasco": {},
                "Valencia": {}
            },
            "Sweden": {},
            "Switzerland": {},
            "Turkey": {},
            "Ukraine": {},
            "United_Kingdom": {
                "England": {},
                "Scotland": {},
                "Wales": {},
                "Northern_Ireland": {}
            }
        },
        
        "North_America": {
            "Canada": {
                "Alberta": {},
                "British_Columbia": {},
                "Manitoba": {},
                "New_Brunswick": {},
                "Newfoundland_and_Labrador": {},
                "Northwest_Territories": {},
                "Nova_Scotia": {},
                "Nunavut": {},
                "Ontario": {},
                "Prince_Edward_Island": {},
                "Quebec": {},
                "Saskatchewan": {},
                "Yukon": {}
            },
            "Greenland": {},
            "Mexico": {},
            "United_States": {
                "Alabama": {},
                "Alaska": {},
                "Arizona": {},
                "Arkansas": {},
                "California": {},
                "Colorado": {},
                "Connecticut": {},
                "Delaware": {},
                "District_of_Columbia": {},
                "Florida": {},
                "Georgia": {},
                "Hawaii": {},
                "Idaho": {},
                "Illinois": {},
                "Indiana": {},
                "Iowa": {},
                "Kansas": {},
                "Kentucky": {},
                "Louisiana": {},
                "Maine": {},
                "Maryland": {},
                "Massachusetts": {},
                "Michigan": {},
                "Minnesota": {},
                "Mississippi": {},
                "Missouri": {},
                "Montana": {},
                "Nebraska": {},
                "Nevada": {},
                "New_Hampshire": {},
                "New_Jersey": {},
                "New_Mexico": {},
                "New_York": {},
                "North_Carolina": {},
                "North_Dakota": {},
                "Ohio": {},
                "Oklahoma": {},
                "Oregon": {},
                "Pennsylvania": {},
                "Puerto_Rico": {},
                "Rhode_Island": {},
                "South_Carolina": {},
                "South_Dakota": {},
                "Tennessee": {},
                "Texas": {},
                "US_Virgin_Islands": {},
                "Utah": {},
                "Vermont": {},
                "Virginia": {},
                "Washington": {},
                "West_Virginia": {},
                "Wisconsin": {},
                "Wyoming": {}
            }
        },
        
        "South_America": {
            "Argentina": {},
            "Bolivia": {},
            "Brazil": {
                "Centro_Oeste": {},
                "Nordeste": {},
                "Norte": {},
                "Sudeste": {},
                "Sul": {}
            },
            "Chile": {
                "Arica_y_Parinacota": {},
                "Tarapaca": {},
                "Antofagasta": {},
                "Atacama": {},
                "Coquimbo": {},
                "Valparaiso": {},
                "Metropolitana": {},
                "O_Higgins": {},
                "Maule": {},
                "Nuble": {},
                "Biobio": {},
                "Araucania": {},
                "Los_Rios": {},
                "Los_Lagos": {},
                "Aysen": {},
                "Magallanes": {}
            },
            "Colombia": {},
            "Ecuador": {},
            "Falkland_Islands": {},
            "French_Guiana": {},
            "Guyana": {},
            "Paraguay": {},
            "Peru": {},
            "Suriname": {},
            "Uruguay": {},
            "Venezuela": {}
        }
    }
    
    print("Creating folder structure for OSM data organization...")
    print("="*60)
    
    total_folders = 0
    
    def create_recursive(path, structure):
        nonlocal total_folders
        for name, sub in structure.items():
            folder_path = path / name
            folder_path.mkdir(parents=True, exist_ok=True)
            total_folders += 1
            
            # Create README in each folder
            readme_path = folder_path / "README.md"
            if not readme_path.exists():
                with open(readme_path, 'w') as f:
                    f.write(f"# {name.replace('_', ' ')}\n\n")
                    f.write(f"Place OSM PBF files here.\n\n")
                    f.write(f"Download from: https://download.geofabrik.de/\n\n")
                    f.write(f"## Extract Data\n")
                    f.write(f"```bash\n")
                    f.write(f"python extract_region.py <filename>\n")
                    f.write(f"```\n")
            
            if sub:  # Has subdirectories
                create_recursive(folder_path, sub)
    
    create_recursive(base, structure)
    
    print(f"\n✅ Created {total_folders} folders")
    print(f"\n📁 Base location: {base}")
    print(f"\nFolder structure matches Geofabrik's organization:")
    print(f"  - 7 Continents")
    print(f"  - 200+ Countries")
    print(f"  - 500+ States/Regions/Provinces")
    print(f"\n💡 Each folder contains a README with download instructions")

if __name__ == "__main__":
    create_folder_structure()
