import React, { useState } from "react";
import { FiDownload, FiFolder, FiX } from "react-icons/fi";
import { useData } from "../context/DataContext";
import JSZip from "jszip";
import { saveAs } from "file-saver";

const ExportCalliope = ({ onExportComplete }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const { locations, links, parameters, getCurrentModel } = useData();

  const generateModelYAML = () => {
    const currentModel = getCurrentModel();
    const modelName = currentModel ? currentModel.name.toLowerCase().replace(/\s+/g, '_') : 'energy_model';

    return `##
# Calliope Model Configuration (v0.6.8)
# Generated by Calliope Visualizator
# Model: ${currentModel?.name || 'Untitled Model'}
##

import:
  - 'model_config/techs.yaml'
  - 'model_config/locations.yaml'

model:
  name: ${modelName}
  timeseries_data_path: 'timeseries_data'
  
run:
  solver: cbc
  mode: plan
  
techs:
  demand_power:
    essentials:
      parent: demand
      carrier: electricity
  
  supply_power:
    essentials:
      parent: supply
      carrier: electricity
    constraints:
      energy_cap_max: 1000
      resource: inf

# Time settings
subset_time: ['2005-01-01', '2005-01-07']
`;
  };

  const generateTechsYAML = () => {
    // Get unique technology types from locations
    const techTypes = [...new Set(locations.map(loc => loc.type))];
    
    let techsConfig = `##
# Technology Definitions
# Generated by Calliope Visualizator
##

techs:
`;

    // Generate tech definitions based on location types
    techTypes.forEach(type => {
      if (type === 'demand') {
        techsConfig += `  demand_power:
    essentials:
      name: 'Power demand'
      parent: demand
      carrier: electricity
    
`;
      } else if (type === 'supply' || type === 'supply_plus') {
        techsConfig += `  supply_power:
    essentials:
      name: 'Power supply'
      parent: ${type === 'supply_plus' ? 'supply_plus' : 'supply'}
      carrier_out: electricity
    constraints:
      resource: inf
      energy_cap_max: 10000
      energy_cap_min: 0
      energy_eff: 1.0
    costs:
      monetary:
        interest_rate: 0.1
        energy_cap: 1000
        om_prod: 0.005
    
`;
      } else if (type === 'storage') {
        techsConfig += `  battery_storage:
    essentials:
      name: 'Battery storage'
      parent: storage
      carrier: electricity
    constraints:
      energy_cap_max: 1000
      storage_cap_max: 10000
      energy_eff: 0.95
      storage_loss: 0.01
    costs:
      monetary:
        interest_rate: 0.1
        energy_cap: 500
        storage_cap: 200
    
`;
      } else if (type === 'conversion' || type === 'conversion_plus') {
        techsConfig += `  conversion_tech:
    essentials:
      name: 'Conversion technology'
      parent: ${type === 'conversion_plus' ? 'conversion_plus' : 'conversion'}
      carrier_in: electricity
      carrier_out: electricity
    constraints:
      energy_cap_max: 5000
      energy_eff: 0.85
    costs:
      monetary:
        interest_rate: 0.1
        energy_cap: 800
        om_prod: 0.01
    
`;
      } else if (type === 'transmission') {
        techsConfig += `  transmission_tech:
    essentials:
      name: 'Transmission technology'
      parent: transmission
      carrier: electricity
    constraints:
      energy_cap_max: 2000
      energy_eff: 0.98
    costs:
      monetary:
        interest_rate: 0.1
        energy_cap: 300
    
`;
      }
    });

    return techsConfig;
  };

  const generateLocationsYAML = () => {
    let locationsConfig = `##
# Location Definitions
# Generated by Calliope Visualizator
##

locations:
`;

    // Add each location
    locations.forEach(loc => {
      const locName = loc.name.toLowerCase().replace(/\s+/g, '_');
      locationsConfig += `  ${locName}:
    coordinates:
      lat: ${loc.lat}
      lon: ${loc.lon}
    techs:
`;

      // Add appropriate tech based on type
      if (loc.type === 'demand') {
        locationsConfig += `      demand_power:
        constraints:
          resource: file=demand_${locName}.csv
`;
      } else if (loc.type === 'supply' || loc.type === 'supply_plus') {
        locationsConfig += `      supply_power:
        constraints:
          resource: file=resource_${locName}.csv
`;
      } else if (loc.type === 'storage') {
        locationsConfig += `      battery_storage:
`;
      } else if (loc.type === 'conversion' || loc.type === 'conversion_plus') {
        locationsConfig += `      conversion_tech:
`;
      }
      locationsConfig += '\n';
    });

    // Add links
    if (links.length > 0) {
      locationsConfig += '\nlinks:\n';
      links.forEach(link => {
        const fromName = link.from.toLowerCase().replace(/\s+/g, '_');
        const toName = link.to.toLowerCase().replace(/\s+/g, '_');
        locationsConfig += `  ${fromName},${toName}:
    techs:
      transmission_tech:
        constraints:
          energy_cap_max: ${link.capacity || 1000}
          energy_cap_min: 0
    distance: ${link.distance || 100}
  
`;
      });
    }

    return locationsConfig;
  };

  const generateTimeseriesCSV = (locationName, type) => {
    // Generate sample time series data
    const hours = 168; // 1 week
    let csv = 'timestep,value\n';
    
    for (let i = 0; i < hours; i++) {
      const timestamp = `2005-01-0${Math.floor(i/24) + 1} ${String(i % 24).padStart(2, '0')}:00:00`;
      let value;
      
      if (type === 'demand') {
        // Demand pattern: higher during day, lower at night
        const hour = i % 24;
        const baseDemand = 50;
        const variation = 30 * Math.sin((hour - 6) * Math.PI / 12);
        value = Math.max(20, baseDemand + variation + Math.random() * 10);
      } else {
        // Resource pattern for supply (e.g., solar-like)
        const hour = i % 24;
        if (hour >= 6 && hour <= 18) {
          value = 100 * Math.sin((hour - 6) * Math.PI / 12) * (0.8 + Math.random() * 0.4);
        } else {
          value = Math.random() * 5;
        }
      }
      
      csv += `${timestamp},${value.toFixed(2)}\n`;
    }
    
    return csv;
  };

  const generateRunScript = () => {
    const currentModel = getCurrentModel();
    const modelName = currentModel ? currentModel.name.toLowerCase().replace(/\s+/g, '_') : 'energy_model';
    
    return `# Calliope Model Run Script
# Generated by Calliope Visualizator

import calliope

# Load and run the model
model = calliope.Model('model.yaml')
model.run()

# Save results
model.to_netcdf('results/${modelName}_results.nc')

# Print summary
print(model.results)
print("\\nModel run completed successfully!")
print(f"Results saved to: results/${modelName}_results.nc")

# Optional: Plot results
# model.plot.timeseries()
`;
  };

  const generateReadme = () => {
    const currentModel = getCurrentModel();
    return `# ${currentModel?.name || 'Calliope Energy Model'}

Generated by Calliope Visualizator on ${new Date().toLocaleString()}

## Model Information
- **Locations**: ${locations.length} nodes
- **Links**: ${links.length} connections
- **Parameters**: ${parameters.length} defined

## Structure
\`\`\`
.
├── model.yaml              # Main model configuration
├── model_config/
│   ├── locations.yaml      # Location and link definitions
│   └── techs.yaml          # Technology definitions
├── timeseries_data/        # Time-series CSV files
│   ├── demand_*.csv        # Demand profiles
│   └── resource_*.csv      # Resource availability
├── run_model.py            # Python script to run the model
└── README.md               # This file
\`\`\`

## Requirements
- Python 3.7+
- Calliope 0.6.8

Install dependencies:
\`\`\`bash
pip install calliope==0.6.8
\`\`\`

## Running the Model

1. Navigate to this directory
2. Run the model:
   \`\`\`bash
   python run_model.py
   \`\`\`

Or use Calliope CLI:
\`\`\`bash
calliope run model.yaml
\`\`\`

## Model Configuration

### Solver
Default solver: CBC (open-source)
To use a different solver (e.g., Gurobi, CPLEX), modify \`model.yaml\`:
\`\`\`yaml
run:
  solver: gurobi  # or cplex, glpk, etc.
\`\`\`

### Time Range
Default: 1 week (2005-01-01 to 2005-01-07)
Modify in \`model.yaml\`:
\`\`\`yaml
subset_time: ['2005-01-01', '2005-12-31']
\`\`\`

## Locations

${locations.map(loc => `- **${loc.name}** (${loc.type}): [${loc.lat}, ${loc.lon}]`).join('\n')}

## Links

${links.length > 0 ? links.map(link => `- ${link.from} ↔ ${link.to}: ${link.capacity || 'N/A'} MW, ${link.distance || 'N/A'} km`).join('\n') : 'No links defined.'}

## Notes
- Time-series data is generated with sample values. Replace with actual data for realistic results.
- Technology parameters are set to default values. Adjust in \`techs.yaml\` as needed.
- For more information, visit: https://calliope.readthedocs.io/
`;
  };

  const handleExport = async () => {
    setIsExporting(true);
    
    try {
      const currentModel = getCurrentModel();
      
      if (!currentModel) {
        alert("No model loaded. Please create or load a model first.");
        setIsExporting(false);
        return;
      }

      const modelName = currentModel.name.toLowerCase().replace(/\s+/g, '_');
      
      // Prepare files structure for storage
      const files = [];
      
      // Add main files
      files.push({ path: "model.yaml", content: generateModelYAML() });
      files.push({ path: "model_config/techs.yaml", content: generateTechsYAML() });
      files.push({ path: "model_config/locations.yaml", content: generateLocationsYAML() });
      files.push({ path: "run_model.py", content: generateRunScript() });
      files.push({ path: "README.md", content: generateReadme() });
      files.push({ path: "results/.gitkeep", content: "" });
      
      // Add time-series files
      locations.forEach(loc => {
        const locName = loc.name.toLowerCase().replace(/\s+/g, '_');
        if (loc.type === 'demand') {
          files.push({
            path: `timeseries_data/demand_${locName}.csv`,
            content: generateTimeseriesCSV(locName, 'demand')
          });
        } else if (loc.type === 'supply' || loc.type === 'supply_plus') {
          files.push({
            path: `timeseries_data/resource_${locName}.csv`,
            content: generateTimeseriesCSV(locName, 'resource')
          });
        }
      });

      // Save to Calliope Models section
      if (onExportComplete) {
        onExportComplete({
          name: currentModel.name,
          files: files
        });
      }

      // Also create ZIP for download
      const zip = new JSZip();
      files.forEach(file => {
        zip.file(file.path, file.content);
      });

      const blob = await zip.generateAsync({ type: "blob" });
      saveAs(blob, `${modelName}_calliope_model.zip`);
      
      setIsExporting(false);
      setIsOpen(false);
      alert("Calliope model exported successfully! Check the 'Calliope Models' section to edit files.");
      
    } catch (error) {
      console.error("Export failed:", error);
      alert("Failed to export model. Please try again.");
      setIsExporting(false);
    }
  };

  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors"
      >
        <FiDownload />
        Export Calliope Model
      </button>

      {isOpen && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[9999] overflow-y-auto p-4"
          onClick={() => setIsOpen(false)}
        >
          <div 
            className="bg-white rounded-lg shadow-xl max-w-2xl w-full my-8 max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between p-6 border-b">
              <div className="flex items-center gap-2">
                <FiFolder className="text-indigo-600 text-xl" />
                <h2 className="text-xl font-semibold text-slate-800">
                  Export Calliope Model
                </h2>
              </div>
              <button
                onClick={() => setIsOpen(false)}
                className="text-slate-400 hover:text-slate-600"
              >
                <FiX size={24} />
              </button>
            </div>

            <div className="p-6">
              <div className="mb-6">
                <h3 className="font-semibold text-slate-800 mb-3">
                  Generated Files Structure:
                </h3>
                <div className="bg-slate-50 p-4 rounded-md font-mono text-sm text-slate-700">
                  <div className="space-y-1">
                    <div>📄 model.yaml</div>
                    <div>📁 model_config/</div>
                    <div className="ml-4">📄 locations.yaml</div>
                    <div className="ml-4">📄 techs.yaml</div>
                    <div>📁 timeseries_data/</div>
                    <div className="ml-4">📄 demand_*.csv ({locations.filter(l => l.type === 'demand').length} files)</div>
                    <div className="ml-4">📄 resource_*.csv ({locations.filter(l => l.type === 'supply' || l.type === 'supply_plus').length} files)</div>
                    <div>📁 results/ (empty, for outputs)</div>
                    <div>📄 run_model.py</div>
                    <div>📄 README.md</div>
                  </div>
                </div>
              </div>

              <div className="mb-6 p-4 bg-blue-50 rounded-md">
                <h4 className="font-semibold text-blue-900 mb-2">ℹ️ Model Details:</h4>
                <ul className="text-sm text-blue-800 space-y-1">
                  <li>• Calliope version: 0.6.8</li>
                  <li>• Locations: {locations.length} nodes</li>
                  <li>• Links: {links.length} connections</li>
                  <li>• Default solver: CBC (open-source)</li>
                  <li>• Time range: 1 week (sample data)</li>
                </ul>
              </div>

              <div className="mb-6 p-4 bg-amber-50 rounded-md border border-amber-200">
                <h4 className="font-semibold text-amber-900 mb-2">⚠️ Important Notes:</h4>
                <ul className="text-sm text-amber-800 space-y-1">
                  <li>• Time-series data contains sample values</li>
                  <li>• Replace CSV files with actual data for production use</li>
                  <li>• Technology parameters are set to defaults</li>
                  <li>• Review and adjust configurations as needed</li>
                </ul>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={handleExport}
                  disabled={isExporting}
                  className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 transition-colors disabled:bg-slate-400 disabled:cursor-not-allowed"
                >
                  {isExporting ? (
                    <>
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                      Generating...
                    </>
                  ) : (
                    <>
                      <FiDownload />
                      Download ZIP
                    </>
                  )}
                </button>
                <button
                  onClick={() => setIsOpen(false)}
                  className="px-6 py-3 border border-slate-300 text-slate-700 rounded-md hover:bg-slate-50 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default ExportCalliope;
