/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#5e5e5e',
        'surface-bright': '#faf8ff',
        'primary-fixed': '#5e5e5e',
        'on-error-container': '#410002',
        'on-tertiary-fixed': '#ffffff',
        'on-surface': '#131b2e',
        'inverse-on-surface': '#eef0ff',
        background: '#faf8ff',
        'secondary-fixed': '#b7c8e1',
        'on-tertiary': '#e2e2e2',
        'surface-dim': '#d2d9f4',
        'on-tertiary-container': '#ffffff',
        'secondary-fixed-dim': '#9cacc5',
        outline: '#777777',
        'on-tertiary-fixed-variant': '#e2e2e2',
        'on-error': '#ffffff',
        'surface-container': '#eaedff',
        primary: '#000000',
        'on-secondary-container': '#0b1c30',
        error: '#ba1a1a',
        'primary-container': '#3b3b3b',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#2d3c51',
        'on-background': '#131b2e',
        'surface-container-highest': '#dae2fd',
        'tertiary-container': '#747474',
        'on-secondary-fixed': '#0b1c30',
        surface: '#faf8ff',
        'tertiary-fixed': '#5e5e5e',
        'secondary-container': '#c5d6f0',
        'on-primary-container': '#ffffff',
        'tertiary-fixed-dim': '#474747',
        tertiary: '#3b3b3b',
        'on-primary': '#e2e2e2',
        'inverse-primary': '#c6c6c6',
        'error-container': '#ffdad6',
        'surface-variant': '#dae2fd',
        'primary-fixed-dim': '#474747',
        'inverse-surface': '#283044',
        secondary: '#505f76',
        'surface-container-low': '#f2f3ff',
        'on-primary-fixed': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#e2e2e2',
        'surface-container-high': '#e2e7ff',
        'outline-variant': '#c6c6c6',
        'on-surface-variant': '#474747',
        foreground: '#131b2e',
        'muted-foreground': '#6b7280',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
